import type { Metadata } from "next";
import { LiquidGlassProvider, ThemeScript } from "@caira/ui/foundations";
import { RouterProvider } from "@caira/ui/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    // suppressHydrationWarning: ThemeScript sets theme attributes on <html> before React hydrates.
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className="min-h-full flex flex-col">
        <RouterProvider>
          <LiquidGlassProvider>{children}</LiquidGlassProvider>
        </RouterProvider>
      </body>
    </html>
  );
}
